### ISSUE TITLE
willow-dialog description seems contradictory & could be confusing to users.

### ISSUE THREAD

**Issue by JSpell** [unumux/willow#12]
While reading through the description for dialog, it seems a bit contradictory.

> Willow-Dialog is a small window that overlays (pops up over) the content of a webpage. Dialogs communicate information to a user and can prompt them with **questions that do not require a response**. If any of your **questions require an answer use the willow-modal component** instead. 

However, the last line & examples imply that there could be an action requiring input from the user.

> The dialog should disappear once the **_user has entered the requested information_**, pressed the esc key, or clicked outside of the response area/window.
> 
> Examples: errors, warnings, **_to collect data_**, to inform users of important information, to provide opt-in options like email signup
> 

This probably could be worded differently.  A suggestion would be to say:

The dialog should disappear once the user has **completed the requested/required action**, pressed the esc key, or clicked outside of the response area/window.

And remove the **to collect data** text from the examples.

**Comment by slkennedy** [comment]
Hey @JSpell can you give some suggestions/examples on what you would change?

**Comment by JSpell** [comment]
A suggestion would be to say:

The dialog should disappear once the user has completed the requested/required action, pressed the esc key, or clicked outside of the response area/window.

And remove the to collect data text from the examples.

**Comment by chuckhendo** [comment]
@slkennedy She does provide an example at the bottom; and I agree with part of it. The part that says _user has entered the requested information_ should probably say _user has completed the requested/required action_, since the user may not be entering any information (there may just be, for example, a willow-button). 

I don't necessarily agree with removing _to collect data_, since a dialog could potentially be used to collect data

**Comment by slkennedy** [comment]
Oops sorry I missed the example @JSpell. So dialogs should not be used to present an action that is required - so I disagree with using "required action".  So how about this?

The dialog should disappear if the user has completed the task or action, pressed the `esc` key, or clicked outside of the dialog.
