### ISSUE TITLE
Banner action styling

### ISSUE THREAD

**Issue by slkennedy** [unumux/willow#19]
Need to remove list style from banner action
![screen shot 2017-04-27 at 3 29 42 pm](https://cloud.githubusercontent.com/assets/7518469/25500796/5e3e55be-2b5e-11e7-8b4f-1b577179a25d.png)

**Comment by dbay24** [comment]
This has been fixed. It was a hyphen vs underscore thang.

**Comment by slkennedy** [comment]
Thanks @dbay24
