### ISSUE TITLE
Page-footer not falling to the bottom when there is little or no page-content

### ISSUE THREAD

**Issue by slkennedy** [unumux/willow#20]
<img width="1213" alt="screen shot 2017-04-28 at 10 31 53 am" src="https://cloud.githubusercontent.com/assets/7518469/25533221/ed50e8a8-2bfd-11e7-9294-2653d021dd6a.png">

**Comment by dbay24** [comment]
I just submitted a pull request for this under "daniel-suggestions". This fix also requires a '--grow' modifier to be added to the index.html file in order to work.
