### ISSUE TITLE
.willow-page-header and .willow-header__branding don't have consistent spacing

### ISSUE THREAD

**Issue by chuckhendo** [unumux/willow#7]
When inserting a .willow-logo-link in .willow-header__branding, the spacing isn't consistent between top and bottom.

![image](https://cloud.githubusercontent.com/assets/1184341/24773653/f98d9a4c-1ae3-11e7-8f37-057646b5624e.png)

**Comment by dbay24** [comment]
I just updated the daniel-suggestions branch to address this. I added more padding-bottom (space(2)) to the branding partial and made the image a block (that removed 6px of random space beneath it) in order to line them up vertically regardless of img size.
