### ISSUE TITLE
Problem when updating to 0.3.0

### ISSUE THREAD

**Issue by townivan** [unumux/willow#86]
So, this is new, but I'm guessing not the main issue:
npm WARN bootstrap@4.0.0-beta requires a peer of popper.js@^1.11.0 but none was installed.

But Gulp breaks with the following:
[15:43:46] gulp-notify: [Error running Gulp] node_modules/bootstrap/scss/_variables.scss
Error: argument `$color` of `darken($color, $amount)` must be a color

Backtrace:
node_modules/bootstrap/scss/_variables.scss:168, in function `darken`
node_modules/bootstrap/scss/_variables.scss:168
on line 168 of node_modules/bootstrap/scss/_variables.scss
>> $link-hover-color:      darken($link-color, 15%) !default;
---------------------------^

**Comment by chuckhendo** [comment]
Did you update the theme and Willow?

**Comment by townivan** [comment]
only willow

**Comment by slkennedy** [comment]
So bootstraps upgrade caused us to have to change the imports in the [bootstrap styles](https://github.com/unumux/willow/blob/master/utilities/vendors/_bootstrap-grid.scss).  I vaguely remember getting this same error during development and I think I corrected it by deleting the node_modules folder and rerunning the install and compiling.  Can you give that a try and see if that helps?

**Comment by townivan** [comment]
woot!  That worked!

For the record, I removed the dependencies in my package.json file, ran "npm prune", added them back in, and ran "npm install"
