### ISSUE TITLE
Remove bootstrap container overrides

### ISSUE THREAD

**Issue by Keale2** [unumux/willow#95]
These overrides complicate the use of multiple containers per page. It causes containers to have a min-height of 100vh, which should not be the responsibility of this element.

https://github.com/unumux/willow/blob/cb2f038466752abf0cbe954abb3ed6fd13cc305e/utilities/vendors/overrides/_bootstrap-overrides.scss#L1

**Comment by townivan** [comment]
Doesn't .container need a min-height of 100vh for row-grow to work?  I just ran into a bug with ie11 not working with row-grow and I fixed it by adding height: 100vh to .container.  (because ie11 flexbox needs both height and min-height)  

It wasn't working from those settings on body

**Comment by slkennedy** [comment]
To clarify - the plan is to remove the override styles and put them on another component. That way we aren't altering the Bootstrap components and we can accomplish the issue you point out with our own component.
